languageCode = "zh-cn"                                 # 网站使用的语言代码
languageName = "Simplified Chinese (China)"            # 网站使用的语言名称
weight = 1                                             # 当前语言页面的排序权重
title = "青萍之末"                             # 网页标题

# 参数配置
[params]
  displayName = "中文"                                  # 显示的语言名称
  isoCode = "zh-cn"                                    # 国际标准语言代码
  rtl = false                                          # 是否是从右到左的语言
  dateFormat = "2006年1月2日"                           # 日期格式
 # logo = "img/logo.png"                                            # 网站标志图片路径
 # secondaryLogo = "img/logo.png"           # 第二标志图片路径
  description = "JiBinquan的博客"                       # 网站的描述
  copyright = ":copyright: { year } Ji Binquan"        # 版权信息，包含动态的年份占位符

# 作者信息
[author]
  name = "Ji Binquan"                                  # 作者姓名
  image = "img/avatar.jpg"                            # 作者头像图片路径
  headline = "随便写写，反正也没人看"                                 # 作者的口号或座右铭
  bio = "现在也没研究明白"                         # 作者的简短传记
  # 作者的社交媒体链接列表，还可以添加更多
  links = [
    { zhihu = "https://www.zhihu.com/people/herb-42-46" },    # 知乎链接
    { github = "https://github.com/JiBinquan" },    # GitHub 链接
    { email = "mailto:haing6@163.com" },     # 电子邮件链接
  ]
