[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Friends"
pageRef = "friends"
weight = 20

[[main]]
name = "Statistics"
pageRef = "statistics"
weight = 30

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 30
